CREATE TABLE exam
(
    exam_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_at              TIMESTAMP WITHOUT TIME ZONE,
    initial_difficulty  INTEGER                                 NOT NULL,
    adjusted_difficulty INTEGER,
    survey_id           BIGINT                                  NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_exam PRIMARY KEY (exam_id)
);

CREATE TABLE exam_answer
(
    question_id        BIGINT,
    audio_url          VARCHAR(500),
    stt_script         TEXT,
    improved_answer    TEXT,
    status             VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    exam_id            BIGINT  NOT NULL,
    question_order     INTEGER NOT NULL,
    logic_feedback     TEXT,
    fluency_feedback   TEXT,
    relevance_feedback TEXT,
    grammar_score      INTEGER,
    vocab_score        INTEGER,
    logic_score        INTEGER,
    fluency_score      INTEGER,
    relevance_score    INTEGER,
    CONSTRAINT pk_exam_answer PRIMARY KEY (exam_id, question_order)
);

CREATE TABLE exam_question_set
(
    exam_id         BIGINT  NOT NULL,
    question_order  INTEGER NOT NULL,
    question_set_id BIGINT  NOT NULL,
    CONSTRAINT pk_exam_question_set PRIMARY KEY (exam_id, question_order)
);

CREATE TABLE exam_report
(
    exam_id       BIGINT NOT NULL,
    avg_grammar   DECIMAL(5, 2),
    avg_vocab     DECIMAL(5, 2),
    avg_logic     DECIMAL(5, 2),
    avg_fluency   DECIMAL(5, 2),
    avg_relevance DECIMAL(5, 2),
    total_score   DECIMAL(5, 2),
    grade         VARCHAR(255),
    comment       TEXT,
    strength_type VARCHAR(100),
    weakness_type VARCHAR(100),
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_exam_report PRIMARY KEY (exam_id)
);

CREATE TABLE exam_sentence_feedback
(
    feedback_id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    target_sentence            VARCHAR(255),
    target_segment             VARCHAR(255),
    corrected_segment          VARCHAR(255),
    comment                    VARCHAR(255),
    sentence_order             INTEGER,
    created_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    exam_answer_exam_id        BIGINT,
    exam_answer_question_order INTEGER,
    CONSTRAINT pk_exam_sentence_feedback PRIMARY KEY (feedback_id)
);

CREATE TABLE practice
(
    practice_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    started_at    TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT                                  NOT NULL,
    question_type BIGINT,
    topic_id      BIGINT                                  NOT NULL,
    set_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_practice PRIMARY KEY (practice_id)
);

CREATE TABLE practice_answers
(
    practice_answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    korean_script      TEXT,
    english_script     TEXT,
    english_record_url TEXT,
    practice_id        BIGINT                                  NOT NULL,
    question_id        BIGINT                                  NOT NULL,
    set_id             BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    improved_answer    TEXT,
    relevance_feedback TEXT,
    logic_feedback     TEXT,
    fluency_feedback   TEXT,
    feedback_status    VARCHAR(255),
    CONSTRAINT pk_practice_answers PRIMARY KEY (practice_answer_id)
);

CREATE TABLE practice_question
(
    practice_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL
);

CREATE TABLE practice_sentence_feedback
(
    feedback_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    target_sentence    TEXT,
    target_segment     TEXT,
    improved_segment   TEXT,
    comment            TEXT,
    sentence_order     INTEGER,
    sentence_score     INTEGER,
    practice_answer_id BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_practice_sentence_feedback PRIMARY KEY (feedback_id)
);

CREATE TABLE question_bank
(
    question_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_text TEXT                                    NOT NULL,
    audio_url     TEXT                                    NOT NULL,
    order_index   INTEGER,
    set_id        BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_question_bank PRIMARY KEY (question_id)
);

CREATE TABLE question_set
(
    set_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level        INTEGER                                 NOT NULL,
    question_cnt INTEGER,
    topic_id     BIGINT                                  NOT NULL,
    type_id      BIGINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_question_set PRIMARY KEY (set_id)
);

CREATE TABLE survey
(
    survey_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    occupation  VARCHAR(255),
    teach_at    VARCHAR(255),
    has_job     BOOLEAN,
    work_period VARCHAR(255),
    is_manager  BOOLEAN,
    is_student  BOOLEAN,
    class_type  VARCHAR(255),
    residence   VARCHAR(255),
    level       INTEGER,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_survey PRIMARY KEY (survey_id)
);

CREATE TABLE survey_topics
(
    survey_id BIGINT NOT NULL,
    topic_id  BIGINT NOT NULL
);

CREATE TABLE topic
(
    topic_id    BIGINT      NOT NULL,
    topic_code  VARCHAR(50) NOT NULL,
    topic_name  VARCHAR(50) NOT NULL,
    category_id BIGINT      NOT NULL,
    CONSTRAINT pk_topic PRIMARY KEY (topic_id)
);

CREATE TABLE topic_category
(
    category_id   BIGINT      NOT NULL,
    category_code VARCHAR(50) NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_topic_category PRIMARY KEY (category_id)
);

CREATE TABLE user_roles
(
    user_id BIGINT      NOT NULL,
    role    VARCHAR(20) NOT NULL
);

CREATE TABLE users
(
    user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider          VARCHAR(30)                             NOT NULL,
    provider_id       VARCHAR(50)                             NOT NULL,
    name              VARCHAR(30),
    profile_image_url VARCHAR(500),
    email             VARCHAR(256),
    current_level     VARCHAR(20),
    target_level      VARCHAR(20),
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uk_user_provider_provider_id UNIQUE (provider, provider_id);

ALTER TABLE exam_answer
    ADD CONSTRAINT FK_EXAM_ANSWER_ON_EXAM FOREIGN KEY (exam_id) REFERENCES exam (exam_id);

ALTER TABLE exam_report
    ADD CONSTRAINT FK_EXAM_REPORT_ON_EXAM FOREIGN KEY (exam_id) REFERENCES exam (exam_id);

ALTER TABLE exam_sentence_feedback
    ADD CONSTRAINT FK_EXAM_SENTENCE_FEEDBACK_ON_EXEXIDEXQUOR FOREIGN KEY (exam_answer_exam_id, exam_answer_question_order) REFERENCES exam_answer (exam_id, question_order);

ALTER TABLE practice_answers
    ADD CONSTRAINT FK_PRACTICE_ANSWERS_ON_PRACTICE FOREIGN KEY (practice_id) REFERENCES practice (practice_id);

ALTER TABLE practice_answers
    ADD CONSTRAINT FK_PRACTICE_ANSWERS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question_bank (question_id);

ALTER TABLE practice_answers
    ADD CONSTRAINT FK_PRACTICE_ANSWERS_ON_SET FOREIGN KEY (set_id) REFERENCES question_set (set_id);

ALTER TABLE practice
    ADD CONSTRAINT FK_PRACTICE_ON_SET FOREIGN KEY (set_id) REFERENCES question_set (set_id);

ALTER TABLE practice
    ADD CONSTRAINT FK_PRACTICE_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topic (topic_id);

ALTER TABLE practice
    ADD CONSTRAINT FK_PRACTICE_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE practice_sentence_feedback
    ADD CONSTRAINT FK_PRACTICE_SENTENCE_FEEDBACK_ON_PRACTICE_ANSWER FOREIGN KEY (practice_answer_id) REFERENCES practice_answers (practice_answer_id);

ALTER TABLE question_bank
    ADD CONSTRAINT FK_QUESTION_BANK_ON_SET FOREIGN KEY (set_id) REFERENCES question_set (set_id);

ALTER TABLE question_set
    ADD CONSTRAINT FK_QUESTION_SET_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topic (topic_id);

ALTER TABLE topic
    ADD CONSTRAINT FK_TOPIC_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES topic_category (category_id);

ALTER TABLE exam_question_set
    ADD CONSTRAINT fk_exaqueset_on_exam FOREIGN KEY (exam_id) REFERENCES exam (exam_id);

ALTER TABLE exam_question_set
    ADD CONSTRAINT fk_exaqueset_on_question_set FOREIGN KEY (question_set_id) REFERENCES question_set (set_id);

ALTER TABLE practice_question
    ADD CONSTRAINT fk_practice_question_on_practice FOREIGN KEY (practice_id) REFERENCES practice (practice_id);

ALTER TABLE survey_topics
    ADD CONSTRAINT fk_survey_topics_on_survey FOREIGN KEY (survey_id) REFERENCES survey (survey_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);